name: Sync Fork

on:
  schedule:
    - cron: '0 8 * * *' # This cron job runs daily at 8AM UTC
  workflow_dispatch: # Allows you to run the workflow manually from the Actions tab

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
    # REQUIRED step
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout target repo
      uses: actions/checkout@v3
      with:
        # optional: set the branch to checkout,
        # sync action checks out your 'target_sync_branch' anyway
        ref:  'test-sync'

    # REQUIRED step
    # Step 2: run the sync action
    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        # REQUIRED 'target_repo_token' exactly like this!
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_repo: 'google-gemini/cookbook'
        upstream_sync_branch: 'main'
        target_sync_branch: 'test-sync'
        target_sync_method: 'rebase'

